# Generated by Django 5.1.7 on 2025-03-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.FilePathField()),
                ("size", models.IntegerField()),
            ],
            options={
                "db_table": "docs",
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_type", models.TextField()),
                ("price", models.DecimalField(decimal_places=3, max_digits=20)),
            ],
            options={
                "db_table": "price",
            },
        ),
        migrations.CreateModel(
            name="User_doc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=35)),
                (
                    "docs",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp1.document",
                    ),
                ),
            ],
            options={
                "db_table": "users_docs",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_price", models.DecimalField(decimal_places=3, max_digits=10)),
                ("payment", models.BooleanField(default=False)),
                (
                    "docs",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp1.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp1.user_doc",
                    ),
                ),
            ],
            options={
                "db_table": "cart",
            },
        ),
    ]
