# Generated by Django 5.1.7 on 2025-04-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0004_alter_document_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_doc",
            name="docs",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp1.document",
            ),
        ),
    ]
